# Generated by Django 4.1.7 on 2023-03-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128, unique=True, verbose_name='api密钥')),
                ('call_count', models.BigIntegerField(default=0, verbose_name='调用次数')),
                ('is_work', models.BooleanField(default=True, verbose_name='是否使用')),
                ('is_valid', models.BooleanField(default=True, verbose_name='key是否能用')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('edited_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
