# Generated by Django 4.1.7 on 2023-03-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='balance',
            field=models.BigIntegerField(default=0, verbose_name='剩余调用次数'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='is_work',
            field=models.BooleanField(default=False, verbose_name='是否正在使用使用'),
        ),
    ]
